"""empty message

Revision ID: 0ac247a6136f
Revises: c75a8cad7f72
Create Date: 2024-02-29 13:38:12.940853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac247a6136f'
down_revision = 'c75a8cad7f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
