"""empty message

Revision ID: 215571628012
Revises: e3587267e885
Create Date: 2024-03-02 12:06:03.226932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215571628012'
down_revision = 'e3587267e885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('quantity_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_available', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
