"""empty message

Revision ID: 242cc5001efb
Revises: 8bbe454348c8
Create Date: 2024-02-28 11:08:56.951256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242cc5001efb'
down_revision = '8bbe454348c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageType', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('imageType')

    # ### end Alembic commands ###
