"""empty message

Revision ID: 2680930e3e40
Revises: 17d245d201e9
Create Date: 2024-02-28 21:56:54.659314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2680930e3e40'
down_revision = '17d245d201e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
