"""empty message

Revision ID: 33be53e27f10
Revises: a7f25384eb0a
Create Date: 2024-03-05 16:30:04.354857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33be53e27f10'
down_revision = 'a7f25384eb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
