"""empty message

Revision ID: 674c7da9ea14
Revises: f7b3bffac6eb
Create Date: 2024-03-27 14:57:01.536888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674c7da9ea14'
down_revision = 'f7b3bffac6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_request', schema=None) as batch_op:
        batch_op.drop_column('response')

    # ### end Alembic commands ###
