"""empty message

Revision ID: 7141aa6404c1
Revises: fe886d6e9807
Create Date: 2024-03-04 12:57:32.082185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7141aa6404c1'
down_revision = 'fe886d6e9807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_column('access_revoked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_revoked', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
