"""empty message

Revision ID: 8a951086f265
Revises: 33be53e27f10
Create Date: 2024-03-06 23:05:41.387230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a951086f265'
down_revision = '33be53e27f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_content', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('pdf_file_name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('pdf_file_name')
        batch_op.drop_column('pdf_content')

    # ### end Alembic commands ###
