"""empty message

Revision ID: c75a8cad7f72
Revises: 0cdc672fbee8
Create Date: 2024-02-29 13:18:17.766690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75a8cad7f72'
down_revision = '0cdc672fbee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('estimated_return_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extended_return_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reissue_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_column('reissue_count')
        batch_op.drop_column('extended_return_date')
        batch_op.drop_column('estimated_return_date')
        batch_op.drop_column('late')

    # ### end Alembic commands ###
