"""empty message

Revision ID: e2914a7673a0
Revises: c880633a9716
Create Date: 2024-03-07 10:30:12.272080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2914a7673a0'
down_revision = 'c880633a9716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('pdf_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_content', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
