"""empty message

Revision ID: e3587267e885
Revises: 841167ee0378
Create Date: 2024-02-29 14:46:42.218447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3587267e885'
down_revision = '841167ee0378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
