"""empty message

Revision ID: ef72f1bf6415
Revises: 53cf08e96489
Create Date: 2024-03-20 16:25:21.500897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef72f1bf6415'
down_revision = '53cf08e96489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('balance')

    with op.batch_alter_table('transaction_log', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
