"""empty message

Revision ID: fe886d6e9807
Revises: 215571628012
Create Date: 2024-03-04 11:53:51.966526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe886d6e9807'
down_revision = '215571628012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_revoked', sa.Boolean(), nullable=True))
        batch_op.drop_column('late')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('access_revoked')

    # ### end Alembic commands ###
